create table public.fx_report_runs (
  id uuid primary key default gen_random_uuid(),
  base_date date not null,
  attempt integer not null check (attempt > 0),
  schema_version text not null,
  generation_mode text not null check (generation_mode in ('deterministic', 'ai_enhanced')),
  publish_mode text not null check (publish_mode in ('review', 'automatic')),
  status text not null default 'pending_review'
    check (status in ('pending_review', 'published', 'rejected', 'superseded', 'failed')),
  evidence jsonb not null,
  deterministic_content jsonb not null,
  ai_candidate jsonb,
  selected_content jsonb not null,
  ai_provider text,
  ai_model text,
  raw_ai_response text,
  validation jsonb not null default '{"valid":true,"errors":[]}'::jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (base_date, attempt)
);

create table public.fx_report_reviews (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.fx_report_runs(id),
  decision text not null check (decision in ('approved', 'rejected')),
  reason text check (reason is null or char_length(reason) <= 500),
  reviewed_by_email text not null,
  reviewed_at timestamptz not null default now(),
  unique (run_id)
);

create table public.fx_reports (
  base_date date primary key,
  run_id uuid not null unique references public.fx_report_runs(id),
  schema_version text not null,
  generation_mode text not null check (generation_mode in ('deterministic', 'ai_enhanced')),
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  content jsonb not null,
  evidence jsonb not null,
  published_at timestamptz not null default now()
);

create index fx_report_runs_base_date_created_idx
  on public.fx_report_runs (base_date desc, created_at desc);
create index fx_report_runs_pending_idx
  on public.fx_report_runs (created_at desc)
  where status = 'pending_review';
create index fx_reports_published_idx
  on public.fx_reports (base_date desc, published_at desc);

alter table public.fx_report_runs enable row level security;
alter table public.fx_report_reviews enable row level security;
alter table public.fx_reports enable row level security;

revoke all on table public.fx_report_runs from anon, authenticated;
revoke all on table public.fx_report_reviews from anon, authenticated;
revoke all on table public.fx_reports from anon, authenticated;
revoke all on sequence public.fx_report_reviews_id_seq from anon, authenticated;

grant select on table public.fx_reports to anon, authenticated;
grant select on table public.fx_report_runs to authenticated;
grant select on table public.fx_report_reviews to authenticated;
grant select, insert, update, delete on table public.fx_report_runs to service_role;
grant select, insert on table public.fx_report_reviews to service_role;
grant select, insert, update, delete on table public.fx_reports to service_role;
grant usage, select on sequence public.fx_report_reviews_id_seq to service_role;

create policy "Published FX reports are public"
on public.fx_reports for select
to anon, authenticated
using (true);

create policy "Active admins can view FX report runs"
on public.fx_report_runs for select
to authenticated
using ((select app_private.is_business_plan_admin()));

create policy "Active admins can view FX report reviews"
on public.fx_report_reviews for select
to authenticated
using ((select app_private.is_business_plan_admin()));

create or replace function app_private.review_fx_report(
  p_run_id uuid,
  p_decision text,
  p_reason text default null
)
returns public.fx_report_runs
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower((select auth.jwt()) ->> 'email');
  v_run public.fx_report_runs;
begin
  if (select auth.uid()) is null or v_email is null or not (select app_private.is_business_plan_admin()) then
    raise exception 'active administrator access required' using errcode = '42501';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'decision must be approved or rejected' using errcode = '22023';
  end if;

  select * into v_run
  from public.fx_report_runs
  where id = p_run_id
  for update;

  if v_run.id is null then
    raise exception 'report run not found' using errcode = 'P0002';
  end if;
  if v_run.status <> 'pending_review' then
    raise exception 'report run is no longer pending review' using errcode = '55000';
  end if;

  insert into public.fx_report_reviews(run_id, decision, reason, reviewed_by_email)
  values (p_run_id, p_decision, nullif(trim(p_reason), ''), v_email);

  if p_decision = 'approved' then
    insert into public.fx_reports(
      base_date, run_id, schema_version, generation_mode, confidence,
      content, evidence, published_at
    ) values (
      v_run.base_date, v_run.id, v_run.schema_version, v_run.generation_mode,
      coalesce(v_run.selected_content ->> 'confidence', v_run.evidence ->> 'confidence', 'low'),
      v_run.selected_content, v_run.evidence, now()
    )
    on conflict (base_date) do update set
      run_id = excluded.run_id,
      schema_version = excluded.schema_version,
      generation_mode = excluded.generation_mode,
      confidence = excluded.confidence,
      content = excluded.content,
      evidence = excluded.evidence,
      published_at = excluded.published_at;

    update public.fx_report_runs
    set status = 'published', published_at = now()
    where id = p_run_id
    returning * into v_run;
  else
    update public.fx_report_runs
    set status = 'rejected'
    where id = p_run_id
    returning * into v_run;
  end if;

  return v_run;
end;
$$;

revoke all on function app_private.review_fx_report(uuid, text, text)
  from public, anon, authenticated;
grant execute on function app_private.review_fx_report(uuid, text, text)
  to authenticated;

create or replace function public.review_fx_report(
  p_run_id uuid,
  p_decision text,
  p_reason text default null
)
returns public.fx_report_runs
language sql
security invoker
set search_path = ''
as $$
  select app_private.review_fx_report(p_run_id, p_decision, p_reason);
$$;

revoke all on function public.review_fx_report(uuid, text, text) from public, anon;
grant execute on function public.review_fx_report(uuid, text, text) to authenticated;

create or replace function public.publish_fx_report_system(p_run_id uuid)
returns public.fx_report_runs
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_run public.fx_report_runs;
begin
  select * into v_run
  from public.fx_report_runs
  where id = p_run_id
  for update;

  if v_run.id is null then
    raise exception 'report run not found' using errcode = 'P0002';
  end if;
  if v_run.status <> 'pending_review' then
    raise exception 'report run is no longer pending review' using errcode = '55000';
  end if;

  insert into public.fx_reports(
    base_date, run_id, schema_version, generation_mode, confidence,
    content, evidence, published_at
  ) values (
    v_run.base_date, v_run.id, v_run.schema_version, v_run.generation_mode,
    coalesce(v_run.selected_content ->> 'confidence', v_run.evidence ->> 'confidence', 'low'),
    v_run.selected_content, v_run.evidence, now()
  )
  on conflict (base_date) do update set
    run_id = excluded.run_id,
    schema_version = excluded.schema_version,
    generation_mode = excluded.generation_mode,
    confidence = excluded.confidence,
    content = excluded.content,
    evidence = excluded.evidence,
    published_at = excluded.published_at;

  update public.fx_report_runs
  set status = 'published', published_at = now()
  where id = p_run_id
  returning * into v_run;

  return v_run;
end;
$$;

revoke all on function public.publish_fx_report_system(uuid) from public, anon, authenticated;
grant execute on function public.publish_fx_report_system(uuid) to service_role;

comment on table public.fx_report_runs is
  'Private report generation attempts. RLS restricts browser reads to active administrators.';
comment on table public.fx_reports is
  'Sanitized reports approved for public dashboard and email display.';
